"""add attire and contact fields to events

Revision ID: 8202f93bb2fb
Revises: 5c1511bffa16
Create Date: 2025-11-10 22:27:20.167416

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8202f93bb2fb"
down_revision = "5c1511bffa16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "attire",
            sa.String(length=100),
            nullable=True,
            comment="Dress code or attire (e.g., 'Black Tie', 'Cocktail Attire', 'Business Casual')",
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "primary_contact_name",
            sa.String(length=255),
            nullable=True,
            comment="Primary contact person for event inquiries",
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "primary_contact_email",
            sa.String(length=255),
            nullable=True,
            comment="Email address for event inquiries",
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "primary_contact_phone",
            sa.String(length=20),
            nullable=True,
            comment="Phone number for event inquiries",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "primary_contact_phone")
    op.drop_column("events", "primary_contact_email")
    op.drop_column("events", "primary_contact_name")
    op.drop_column("events", "attire")
    # ### end Alembic commands ###
